### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by RainbowMango** [JCCE-nudt/karmada-dashboard#1]
不熟悉JS，是我环境上的node.js版本太低吗？
```bash
# npm run dev

> karmada-dashboard@0.1.0 dev /root/go/src/github.com/karmada-io/karmada-dashboard
> vue-cli-service serve

/root/go/src/github.com/karmada-io/karmada-dashboard/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/go/src/github.com/karmada-io/karmada-dashboard/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 3.10.0-1062.12.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! karmada-dashboard@0.1.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the karmada-dashboard@0.1.0 dev script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the karmada-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs karmada-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls karmada-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/go/src/github.com/karmada-io/karmada-dashboard/npm-debug.log

```

**Comment by jhnine** [comment]
经排查是node.js版本过低的原因，需要[升级版本](https://nodejs.org/zh-cn/download/releases/)到v8.17.0以上

**Comment by RainbowMango** [comment]
OK. Thanks.
I've updated the node and will try again.
```bash
# node -v 
v16.13.1
```

**Comment by RainbowMango** [comment]
```
# npm install
npm ERR! Linux 3.10.0-1062.12.1.el7.x86_64
npm ERR! argv "/usr/local/lib/nodejs/bin/node" "/usr/bin/npm" "install"
npm ERR! node v16.13.1
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/go/src/github.com/karmada-io/karmada-dashboard/npm-debug.log
```

这是什么问题？
```bash
# cat /root/go/src/github.com/karmada-io/karmada-dashboard/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/nodejs/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v16.13.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack TypeError: cb.apply is not a function
7 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/graceful-fs/polyfills.js:267:18
7 verbose stack     at FSReqCallback.oncomplete (node:fs:199:5)
8 verbose cwd /root/go/src/github.com/karmada-io/karmada-dashboard
9 error Linux 3.10.0-1062.12.1.el7.x86_64
10 error argv "/usr/local/lib/nodejs/bin/node" "/usr/bin/npm" "install"
11 error node v16.13.1
12 error npm  v3.10.10
13 error cb.apply is not a function
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

**Comment by RainbowMango** [comment]
没意识到npm版本太旧了。现在升级到v8.1.2解决了
```
# npm -v 
8.1.2

```

**Comment by RainbowMango** [comment]
![image](https://user-images.githubusercontent.com/8268873/145393358-583a48b8-c1ec-426b-a93f-aca1cc245a1c.png)

**Comment by gf457832386** [comment]
> ![image](https://user-images.githubusercontent.com/8268873/145393358-583a48b8-c1ec-426b-a93f-aca1cc245a1c.png)

 生成token链接：https://github.com/JCCE-nudt/karmada-dashboard/blob/main/docs/creating-sample-user.md

**Comment by RainbowMango** [comment]
是的，我看到了。现在还没看把dashboard部署 集群中的文档。
